# Generated by Django 4.0.2 on 2022-02-08 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='account',
        ),
    ]
